// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ISeed is an autogenerated mock type for the ISeed type
type ISeed struct {
	mock.Mock
}

// InvestorSeed provides a mock function with given fields:
func (_m *ISeed) InvestorSeed() {
	_m.Called()
}

// OutboxSeed provides a mock function with given fields: ctx
func (_m *ISeed) OutboxSeed(ctx context.Context) {
	_m.Called(ctx)
}

// NewISeed creates a new instance of ISeed. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISeed(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISeed {
	mock := &ISeed{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
