// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HashPassword is an autogenerated mock type for the HashPassword type
type HashPassword struct {
	mock.Mock
}

// HashedPassword provides a mock function with given fields: password
func (_m *HashPassword) HashedPassword(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPassword provides a mock function with given fields: hashed, password
func (_m *HashPassword) VerifyPassword(hashed string, password string) error {
	ret := _m.Called(hashed, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashed, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHashPassword creates a new instance of HashPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashPassword {
	mock := &HashPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
